# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.cache/wt [current_project]
set_property parent.project_path E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.srcs/sources_1/new/PPS_Delay.v
  E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.srcs/sources_1/new/PWM_Gen.v
  E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.srcs/sources_1/new/clk_div.v
  E:/PPS_Syn/PPS_Syn_Uart/uart_rx.v
  E:/PPS_Syn/PPS_Syn_Uart/uart_tx.v
  E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.srcs/sources_1/new/PPS_delay_Uart.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.srcs/constrs_1/new/PPS_drc.xdc
set_property used_in_implementation false [get_files E:/PPS_Syn/PPS_Syn_Uart/PPS_Syn_Uart.srcs/constrs_1/new/PPS_drc.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top PPS_delay_Uart -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PPS_delay_Uart.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PPS_delay_Uart_utilization_synth.rpt -pb PPS_delay_Uart_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
