set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property PACKAGE_PIN F20 [get_ports rst_n]
set_property PACKAGE_PIN G16 [get_ports uart_tx]
set_property PACKAGE_PIN G15 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
